title: "Chronic IT"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: true
aux_links:
    "Cafe Gamma":
      - "//cafegamma.com"
footer_content: "Want to get in touch? Send an email to info at chronicit.com"